const forms = [
  {
    'sing:masc:nomn': 'сатанинский',
    'sing:masc:gent': 'сатанинского',
    'sing:masc:datv': 'сатанинскому',
    'sing:masc:accs': 'сатанинский',
    'sing:masc:ablt': 'сатанинским',
    'sing:masc:loct': 'сатанинском',
    'sing:femn:nomn': 'сатанинская',
    'sing:femn:gent': 'сатанинской',
    'sing:femn:datv': 'сатанинской',
    'sing:femn:accs': 'сатанинскую',
    'sing:femn:ablt': 'сатанинской',
    'sing:femn:loct': 'сатанинской',
    'sing:neut:nomn': 'сатанинское',
    'sing:neut:gent': 'сатанинского',
    'sing:neut:datv': 'сатанинскому',
    'sing:neut:accs': 'сатанинское',
    'sing:neut:ablt': 'сатанинским',
    'sing:neut:loct': 'сатанинском',
    'plur:nomn': 'сатанинские',
    'plur:gent': 'сатанинских',
    'plur:datv': 'сатанинским',
    'plur:accs': 'сатанинские',
    'plur:ablt': 'сатанинскими',
    'plur:loct': 'сатанинских',
  },

  {
    'sing:masc:nomn': 'ужасный',
    'sing:masc:gent': 'ужасного',
    'sing:masc:datv': 'ужасному',
    'sing:masc:accs': 'ужасный',
    'sing:masc:ablt': 'ужасным',
    'sing:masc:loct': 'ужасном',
    'sing:femn:nomn': 'ужасная',
    'sing:femn:gent': 'ужасной',
    'sing:femn:datv': 'ужасной',
    'sing:femn:accs': 'ужасную',
    'sing:femn:ablt': 'ужасной',
    'sing:femn:loct': 'ужасной',
    'sing:neut:nomn': 'ужасное',
    'sing:neut:gent': 'ужасного',
    'sing:neut:datv': 'ужасному',
    'sing:neut:accs': 'ужасное',
    'sing:neut:ablt': 'ужасным',
    'sing:neut:loct': 'ужасном',
    'plur:nomn': 'ужасные',
    'plur:gent': 'ужасных',
    'plur:datv': 'ужасным',
    'plur:accs': 'ужасные',
    'plur:ablt': 'ужасными',
    'plur:loct': 'ужасных',
  },

  {
    'sing:masc:nomn': 'чорный',
    'sing:masc:gent': 'чорного',
    'sing:masc:datv': 'чорному',
    'sing:masc:accs': 'чорный',
    'sing:masc:ablt': 'чорным',
    'sing:masc:loct': 'чорном',
    'sing:femn:nomn': 'чорная',
    'sing:femn:gent': 'чорной',
    'sing:femn:datv': 'чорной',
    'sing:femn:accs': 'чорную',
    'sing:femn:ablt': 'чорной',
    'sing:femn:loct': 'чорной',
    'sing:neut:nomn': 'чорное',
    'sing:neut:gent': 'чорного',
    'sing:neut:datv': 'чорному',
    'sing:neut:accs': 'чорное',
    'sing:neut:ablt': 'чорным',
    'sing:neut:loct': 'чорном',
    'plur:nomn': 'чорные',
    'plur:gent': 'чорных',
    'plur:datv': 'чорным',
    'plur:accs': 'чорные',
    'plur:ablt': 'чорными',
    'plur:loct': 'чорных',
  },

  {
    'sing:masc:nomn': 'кошмарный',
    'sing:masc:gent': 'кошмарного',
    'sing:masc:datv': 'кошмарному',
    'sing:masc:accs': 'кошмарный',
    'sing:masc:ablt': 'кошмарным',
    'sing:masc:loct': 'кошмарном',
    'sing:femn:nomn': 'кошмарная',
    'sing:femn:gent': 'кошмарной',
    'sing:femn:datv': 'кошмарной',
    'sing:femn:accs': 'кошмарную',
    'sing:femn:ablt': 'кошмарной',
    'sing:femn:loct': 'кошмарной',
    'sing:neut:nomn': 'кошмарное',
    'sing:neut:gent': 'кошмарного',
    'sing:neut:datv': 'кошмарному',
    'sing:neut:accs': 'кошмарное',
    'sing:neut:ablt': 'кошмарным',
    'sing:neut:loct': 'кошмарном',
    'plur:nomn': 'кошмарные',
    'plur:gent': 'кошмарных',
    'plur:datv': 'кошмарным',
    'plur:accs': 'кошмарные',
    'plur:ablt': 'кошмарными',
    'plur:loct': 'кошмарных',
  },

  {
    'sing:masc:nomn': 'кладбищенский',
    'sing:masc:gent': 'кладбищенского',
    'sing:masc:datv': 'кладбищенскому',
    'sing:masc:accs': 'кладбищенский',
    'sing:masc:ablt': 'кладбищенским',
    'sing:masc:loct': 'кладбищенском',
    'sing:femn:nomn': 'кладбищенская',
    'sing:femn:gent': 'кладбищенской',
    'sing:femn:datv': 'кладбищенской',
    'sing:femn:accs': 'кладбищенскую',
    'sing:femn:ablt': 'кладбищенской',
    'sing:femn:loct': 'кладбищенской',
    'sing:neut:nomn': 'кладбищенское',
    'sing:neut:gent': 'кладбищенского',
    'sing:neut:datv': 'кладбищенскому',
    'sing:neut:accs': 'кладбищенское',
    'sing:neut:ablt': 'кладбищенским',
    'sing:neut:loct': 'кладбищенском',
    'plur:nomn': 'кладбищенские',
    'plur:gent': 'кладбищенских',
    'plur:datv': 'кладбищенским',
    'plur:accs': 'кладбищенские',
    'plur:ablt': 'кладбищенскими',
    'plur:loct': 'кладбищенских',
  },

  {
    'sing:masc:nomn': 'жуткий',
    'sing:masc:gent': 'жуткого',
    'sing:masc:datv': 'жуткому',
    'sing:masc:accs': 'жуткий',
    'sing:masc:ablt': 'жутким',
    'sing:masc:loct': 'жутком',
    'sing:femn:nomn': 'жуткая',
    'sing:femn:gent': 'жуткой',
    'sing:femn:datv': 'жуткой',
    'sing:femn:accs': 'жуткую',
    'sing:femn:ablt': 'жуткой',
    'sing:femn:loct': 'жуткой',
    'sing:neut:nomn': 'жуткое',
    'sing:neut:gent': 'жуткого',
    'sing:neut:datv': 'жуткому',
    'sing:neut:accs': 'жуткое',
    'sing:neut:ablt': 'жутким',
    'sing:neut:loct': 'жутком',
    'plur:nomn': 'жуткие',
    'plur:gent': 'жутких',
    'plur:datv': 'жутким',
    'plur:accs': 'жуткие',
    'plur:ablt': 'жуткими',
    'plur:loct': 'жутких',
  },

  {
    'sing:masc:nomn': 'ведьмовской',
    'sing:masc:gent': 'ведьмовского',
    'sing:masc:datv': 'ведьмовскому',
    'sing:masc:accs': 'ведьмовской',
    'sing:masc:ablt': 'ведьмовском',
    'sing:masc:loct': 'ведьмовском',
    'sing:femn:nomn': 'ведьмовская',
    'sing:femn:gent': 'ведьмовской',
    'sing:femn:datv': 'ведьмовской',
    'sing:femn:accs': 'ведьмовскую',
    'sing:femn:ablt': 'ведьмовской',
    'sing:femn:loct': 'ведьмовской',
    'sing:neut:nomn': 'ведьмовское',
    'sing:neut:gent': 'ведьмовского',
    'sing:neut:datv': 'ведьмовскому',
    'sing:neut:accs': 'ведьмовское',
    'sing:neut:ablt': 'ведьмовском',
    'sing:neut:loct': 'ведьмовском',
    'plur:nomn': 'ведьмовское',
    'plur:gent': 'ведьмовских',
    'plur:datv': 'ведьмовском',
    'plur:accs': 'ведьмовское',
    'plur:ablt': 'ведьмовскоми',
    'plur:loct': 'ведьмовских',
  },

  {
    'sing:masc:nomn': 'адский',
    'sing:masc:gent': 'адского',
    'sing:masc:datv': 'адскому',
    'sing:masc:accs': 'адский',
    'sing:masc:ablt': 'адским',
    'sing:masc:loct': 'адском',
    'sing:femn:nomn': 'адская',
    'sing:femn:gent': 'адской',
    'sing:femn:datv': 'адской',
    'sing:femn:accs': 'адскую',
    'sing:femn:ablt': 'адской',
    'sing:femn:loct': 'адской',
    'sing:neut:nomn': 'адское',
    'sing:neut:gent': 'адского',
    'sing:neut:datv': 'адскому',
    'sing:neut:accs': 'адское',
    'sing:neut:ablt': 'адским',
    'sing:neut:loct': 'адском',
    'plur:nomn': 'адские',
    'plur:gent': 'адских',
    'plur:datv': 'адским',
    'plur:accs': 'адские',
    'plur:ablt': 'адскими',
    'plur:loct': 'адских',
  },

  {
    'sing:masc:nomn': 'зловещий',
    'sing:masc:gent': 'зловещего',
    'sing:masc:datv': 'зловещему',
    'sing:masc:accs': 'зловещий',
    'sing:masc:ablt': 'зловещим',
    'sing:masc:loct': 'зловещем',
    'sing:femn:nomn': 'зловещая',
    'sing:femn:gent': 'зловещей',
    'sing:femn:datv': 'зловещей',
    'sing:femn:accs': 'зловещую',
    'sing:femn:ablt': 'зловещей',
    'sing:femn:loct': 'зловещей',
    'sing:neut:nomn': 'зловещое',
    'sing:neut:gent': 'зловещего',
    'sing:neut:datv': 'зловещему',
    'sing:neut:accs': 'зловещее',
    'sing:neut:ablt': 'зловещим',
    'sing:neut:loct': 'зловещем',
    'plur:nomn': 'зловещие',
    'plur:gent': 'зловещих',
    'plur:datv': 'зловещим',
    'plur:accs': 'зловещие',
    'plur:ablt': 'зловещими',
    'plur:loct': 'зловещих',
  },

  {
    'sing:masc:nomn': 'кровавый',
    'sing:masc:gent': 'кровавого',
    'sing:masc:datv': 'кровавому',
    'sing:masc:accs': 'кровавый',
    'sing:masc:ablt': 'кровавым',
    'sing:masc:loct': 'кровавом',
    'sing:femn:nomn': 'кровавая',
    'sing:femn:gent': 'кровавой',
    'sing:femn:datv': 'кровавой',
    'sing:femn:accs': 'кровавую',
    'sing:femn:ablt': 'кровавой',
    'sing:femn:loct': 'кровавой',
    'sing:neut:nomn': 'кровавое',
    'sing:neut:gent': 'кровавого',
    'sing:neut:datv': 'кровавому',
    'sing:neut:accs': 'кровавое',
    'sing:neut:ablt': 'кровавым',
    'sing:neut:loct': 'кровавом',
    'plur:nomn': 'кровавые',
    'plur:gent': 'кровавых',
    'plur:datv': 'кровавым',
    'plur:accs': 'кровавые',
    'plur:ablt': 'кровавыми',
    'plur:loct': 'кровавых',
  }
];

module.exports = forms;
